"""
utils/translator.py — Multilingual support for AgriChain pages.
"""
import streamlit as st

TRANSLATIONS = {
    "en": {
        # ── New pages ─────────────────────────────────────────────────────
        "Select Crop": "Select Crop",
        "Sowing Date": "Sowing Date",
        "Get Recommendation": "Get Recommendation",
        "Best Harvest Window": "Best Harvest Window",
        "Expected Price Premium": "Expected Price Premium",
        "Confidence": "Confidence",
        "High": "High", "Medium": "Medium", "Low": "Low",
        "HIGH": "HIGH", "MEDIUM": "MEDIUM", "LOW": "LOW",
        "Score Breakdown": "Score Breakdown",
        "Price Seasonality": "Price Seasonality",
        "Weather Score": "Weather Score",
        "Soil Readiness": "Soil Readiness",
        "Why this recommendation?": "Why this recommendation?",
        "14-Day Price Trend": "14-Day Price Trend",
        "Weather Forecast": "Weather Forecast",
        "Mandi Ranker": "Mandi Ranker",
        "Quantity (Quintals)": "Quantity (Quintals)",
        "Find Best Mandis": "Find Best Mandis",
        "Expected Price": "Expected Price",
        "Transport Cost": "Transport Cost",
        "Net Profit per Qtl": "Net Profit per Qtl",
        "Distance": "Distance",
        "Mandi Net Profit Comparison": "Mandi Net Profit Comparison",
        "Total Earnings": "Total Earnings",
        "Spoilage Assessor": "Spoilage Assessor",
        "Storage Type": "Storage Type",
        "Transit Duration (Hours)": "Transit Duration (Hours)",
        "Assess Spoilage Risk": "Assess Spoilage Risk",
        "Spoilage Risk": "Spoilage Risk",
        "Spoilage Probability": "Probability",
        "Recommended Actions": "Recommended Actions",
        "Cost": "Cost",
        "Effectiveness": "Effectiveness",
        "Full Input Summary": "Full Input Summary",
        "Harvest Window": "Harvest Window",
        "Select District": "Select District",
        # ── Home page ─────────────────────────────────────────────────────
        "Harvest Readiness Intelligence": "Harvest Readiness Intelligence",
        "Crop": "Crop",
        "Mandi Market": "Mandi Market",
        "Distance to Mandi (km)": "Distance to Mandi (km)",
        "Calculate Score": "Calculate Score",
        "Your Harvest Summary": "Your Harvest Summary",
        "When to Sell": "When to Sell",
        "Price Analysis": "Price Analysis",
        "7-Day Avg": "7-Day Avg",
        "30-Day Avg": "30-Day Avg",
        "Price Trend": "Price Trend",
        "Price Score": "Price Score",
        "Top Mandis Comparison": "Top Mandis Comparison",
        "Weather at": "Weather at",
        "5-Day Forecast": "5-Day Forecast",
        "Hot days": "Hot days",
        "Rainy days": "Rainy days",
        "Price": "Price",
        "Weather": "Weather",
        "Storage": "Storage",
        "Transport": "Transport",
        "Why This Recommendation?": "Why This Recommendation?",
        "ML Price Forecast": "ML Price Forecast",
        "In 7 Days": "In 7 Days",
        "In 14 Days": "In 14 Days",
        "In 30 Days": "In 30 Days",
        "7-Day Price Breakdown": "7-Day Price Breakdown (with confidence range)",
        "Historical": "Historical",
        "Predicted": "Predicted",
        "AgriChain AI": "AgriChain AI — Ask About Your Harvest",
        "Ask anything": "Ask anything about your harvest...",
        "configure_msg": "Select your crop, mandi, storage type and distance, then click",
        "ai_help_msg": "After analysis, the AgriChain AI will answer questions about your harvest.",
        "Temp": "Temp", "Humidity": "Humidity", "Wind": "Wind", "Precip": "Precip",
        "UV Index": "UV Index", "PM2.5": "PM2.5",
        "Farm Parameters": "Farm Parameters",
        # ── Spoilage Prevention page ──────────────────────────────────────
        "Spoilage Prevention": "Spoilage Prevention",
        "Days Since Harvest": "Days Since Harvest",
        "Est. Harvest Date": "Est. Harvest Date",
        "Days to Harvest": "Days to Harvest",
        "days": "days", "days stored": "days stored",
        "RISK": "RISK", "RISK ACTION": "RISK ACTION",
        "Prevention Tips": "Prevention Tips",
        "Preservation Actions": "Preservation Actions",
        "Rating": "Rating", "Time": "Time",
        "Best Mandi for Emergency Sale": "Best Mandi for Emergency Sale",
        "No mandi data available": "No mandi data available for this crop.",
        "Avg": "Avg",
        "Risk disclaimer": "Risk calculated from crop sensitivity, storage type, and days stored. Actual risk may vary with local conditions.",
    },
    "hi": {
        # ── New pages ─────────────────────────────────────────────────────
        "Select Crop": "फसल चुनें",
        "Sowing Date": "बुवाई की तारीख",
        "Get Recommendation": "सिफारिश पाएं",
        "Best Harvest Window": "सर्वोत्तम कटाई समय",
        "Expected Price Premium": "अपेक्षित मूल्य प्रीमियम",
        "Confidence": "विश्वास",
        "High": "उच्च", "Medium": "मध्यम", "Low": "कम",
        "HIGH": "उच्च", "MEDIUM": "मध्यम", "LOW": "कम",
        "Score Breakdown": "स्कोर विवरण",
        "Price Seasonality": "मूल्य मौसमीकरण",
        "Weather Score": "मौसम स्कोर",
        "Soil Readiness": "मिट्टी तैयारी",
        "Why this recommendation?": "यह सिफारिश क्यों?",
        "14-Day Price Trend": "14 दिवसीय मूल्य रुझान",
        "Weather Forecast": "मौसम पूर्वानुमान",
        "Mandi Ranker": "मंडी रैंकर",
        "Quantity (Quintals)": "मात्रा (क्विंटल)",
        "Find Best Mandis": "सर्वोत्तम मंडी खोजें",
        "Expected Price": "अपेक्षित मूल्य",
        "Transport Cost": "परिवहन लागत",
        "Net Profit per Qtl": "प्रति क्विंटल शुद्ध लाभ",
        "Distance": "दूरी",
        "Mandi Net Profit Comparison": "मंडी शुद्ध लाभ तुलना",
        "Total Earnings": "कुल कमाई",
        "Spoilage Assessor": "खराबी मूल्यांकन",
        "Storage Type": "भंडारण प्रकार",
        "Transit Duration (Hours)": "पारगमन अवधि (घंटे)",
        "Assess Spoilage Risk": "खराबी जोखिम का आकलन करें",
        "Spoilage Risk": "खराबी जोखिम",
        "Spoilage Probability": "संभावना",
        "Recommended Actions": "अनुशंसित कार्य",
        "Cost": "लागत",
        "Effectiveness": "प्रभावशीलता",
        "Full Input Summary": "पूर्ण इनपुट सारांश",
        "Harvest Window": "कटाई समय",
        "Select District": "जिला चुनें",
        # ── Home page ─────────────────────────────────────────────────────
        "Harvest Readiness Intelligence": "फसल तत्परता बुद्धिमत्ता",
        "Crop": "फसल",
        "Mandi Market": "मंडी बाज़ार",
        "Distance to Mandi (km)": "मंडी की दूरी (कि.मी.)",
        "Calculate Score": "स्कोर गणना करें",
        "Your Harvest Summary": "आपका फसल सारांश",
        "When to Sell": "कब बेचें",
        "Price Analysis": "मूल्य विश्लेषण",
        "7-Day Avg": "7-दिन औसत",
        "30-Day Avg": "30-दिन औसत",
        "Price Trend": "मूल्य रुझान",
        "Price Score": "मूल्य स्कोर",
        "Top Mandis Comparison": "शीर्ष मंडी तुलना",
        "Weather at": "मौसम —",
        "5-Day Forecast": "5-दिन पूर्वानुमान",
        "Hot days": "गर्म दिन",
        "Rainy days": "बारिश के दिन",
        "Price": "मूल्य",
        "Weather": "मौसम",
        "Storage": "भंडारण",
        "Transport": "परिवहन",
        "Why This Recommendation?": "यह सिफारिश क्यों?",
        "ML Price Forecast": "एमएल मूल्य पूर्वानुमान",
        "In 7 Days": "7 दिन में",
        "In 14 Days": "14 दिन में",
        "In 30 Days": "30 दिन में",
        "7-Day Price Breakdown": "7-दिन मूल्य विवरण (विश्वास सीमा)",
        "Historical": "ऐतिहासिक",
        "Predicted": "अनुमानित",
        "AgriChain AI": "एग्रीचेन AI — अपनी फसल के बारे में पूछें",
        "Ask anything": "अपनी फसल के बारे में कुछ भी पूछें...",
        "configure_msg": "साइडबार में फसल, मंडी, भंडारण प्रकार और दूरी चुनें, फिर क्लिक करें",
        "ai_help_msg": "विश्लेषण के बाद, एग्रीचेन AI आपकी फसल के बारे में सवालों का जवाब देगा।",
        "Temp": "तापमान", "Humidity": "आर्द्रता", "Wind": "हवा", "Precip": "वर्षा",
        "UV Index": "यूवी सूचकांक", "PM2.5": "PM2.5",
        "Farm Parameters": "खेत मापदंड",
        # ── Spoilage Prevention page ──────────────────────────────────────
        "Spoilage Prevention": "खराबी रोकथाम",
        "Days Since Harvest": "कटाई के बाद के दिन",
        "Est. Harvest Date": "अनुमानित कटाई तिथि",
        "Days to Harvest": "कटाई तक के दिन",
        "days": "दिन", "days stored": "दिन भंडारित",
        "RISK": "जोखिम", "RISK ACTION": "जोखिम कार्रवाई",
        "Prevention Tips": "रोकथाम सुझाव",
        "Preservation Actions": "संरक्षण कार्रवाई",
        "Rating": "रेटिंग", "Time": "समय",
        "Best Mandi for Emergency Sale": "आपातकालीन बिक्री के लिए सर्वोत्तम मंडी",
        "No mandi data available": "इस फसल के लिए मंडी डेटा उपलब्ध नहीं है।",
        "Avg": "औसत",
        "Risk disclaimer": "जोखिम फसल संवेदनशीलता, भंडारण प्रकार और भंडारित दिनों से गणना किया गया है। वास्तविक जोखिम स्थानीय परिस्थितियों के अनुसार भिन्न हो सकता है।",
    },
    "mr": {
        "Select Crop": "पीक निवडा",
        "Sowing Date": "पेरणी तारीख",
        "Get Recommendation": "शिफारस मिळवा",
        "Best Harvest Window": "सर्वोत्तम कापणी वेळ",
        "Expected Price Premium": "अपेक्षित किंमत प्रीमियम",
        "Confidence": "विश्वास",
        "High": "उच्च", "Medium": "मध्यम", "Low": "कमी",
        "HIGH": "उच्च", "MEDIUM": "मध्यम", "LOW": "कमी",
        "Mandi Ranker": "बाजार क्रमवारी",
        "Spoilage Assessor": "नासाडी मूल्यांकन",
        "Harvest Window": "कापणी वेळ",
        "Select District": "जिल्हा निवडा",
        "Harvest Readiness Intelligence": "कापणी तयारी बुद्धिमत्ता",
        "Crop": "पीक",
        "Mandi Market": "बाजार",
        "Distance to Mandi (km)": "बाजाराचे अंतर (कि.मी.)",
        "Calculate Score": "स्कोर मोजा",
        "Your Harvest Summary": "तुमचा पीक सारांश",
        "When to Sell": "कधी विकावे",
        "Price Analysis": "किंमत विश्लेषण",
        "7-Day Avg": "7-दिवस सरासरी",
        "30-Day Avg": "30-दिवस सरासरी",
        "Price Trend": "किंमत कल",
        "Price Score": "किंमत स्कोर",
        "Top Mandis Comparison": "शीर्ष बाजार तुलना",
        "Weather at": "हवामान —",
        "5-Day Forecast": "5-दिवस अंदाज",
        "Hot days": "उष्ण दिवस",
        "Rainy days": "पावसाळी दिवस",
        "Price": "किंमत",
        "Weather": "हवामान",
        "Storage": "साठवण",
        "Transport": "वाहतूक",
        "Why This Recommendation?": "ही शिफारस का?",
        "ML Price Forecast": "ML किंमत अंदाज",
        "In 7 Days": "7 दिवसांत",
        "In 14 Days": "14 दिवसांत",
        "In 30 Days": "30 दिवसांत",
        "7-Day Price Breakdown": "7-दिवस किंमत तपशील (विश्वास मर्यादा)",
        "Historical": "ऐतिहासिक",
        "Predicted": "अंदाजित",
        "AgriChain AI": "ॲग्रीचेन AI — तुमच्या पिकाबद्दल विचारा",
        "Ask anything": "तुमच्या पिकाबद्दल काहीही विचारा...",
        "configure_msg": "साइडबारमध्ये पीक, बाजार, साठवण प्रकार आणि अंतर निवडा, मग क्लिक करा",
        "ai_help_msg": "विश्लेषणानंतर, ॲग्रीचेन AI तुमच्या पिकाबद्दल प्रश्नांची उत्तरे देईल.",
        "Temp": "तापमान", "Humidity": "आर्द्रता", "Wind": "वारा", "Precip": "पाऊस",
        "UV Index": "यूवी निर्देशांक", "PM2.5": "PM2.5",
        "Farm Parameters": "शेत मापदंड",
        "Expected Price": "अपेक्षित किंमत",
        "Transport Cost": "वाहतूक खर्च",
        "Net Profit per Qtl": "प्रति क्विंटल निव्वळ नफा",
        "Distance": "अंतर",
        "Quantity (Quintals)": "मात्रा (क्विंटल)",
        "Find Best Mandis": "सर्वोत्तम बाजार शोधा",
        "Score Breakdown": "स्कोर तपशील",
        "Price Seasonality": "किंमत हंगामीपणा",
        "Weather Score": "हवामान स्कोर",
        "Soil Readiness": "माती तयारी",
        "Total Earnings": "एकूण कमाई",
        "Mandi Net Profit Comparison": "बाजार निव्वळ नफा तुलना",
        "Why this recommendation?": "ही शिफारस का?",
        "14-Day Price Trend": "14-दिवस किंमत कल",
        "Weather Forecast": "हवामान अंदाज",
        "Storage Type": "साठवण प्रकार",
        "Transit Duration (Hours)": "वाहतूक कालावधी (तास)",
        "Assess Spoilage Risk": "नासाडी जोखीम मूल्यांकन करा",
        "Spoilage Risk": "नासाडी जोखीम",
        "Spoilage Probability": "शक्यता",
        "Recommended Actions": "शिफारसीत कृती",
        "Cost": "खर्च",
        "Effectiveness": "परिणामकारकता",
        "Full Input Summary": "पूर्ण इनपुट सारांश",
    },
}


def t(key: str, lang_code: str = "en") -> str:
    """Translate a key into the given language, fallback to English then key."""
    return TRANSLATIONS.get(lang_code, TRANSLATIONS["en"]).get(key, 
           TRANSLATIONS["en"].get(key, key))


def render_lang_sidebar() -> str:
    """Render language selector in sidebar and return language code."""
    opts = {"English": "en", "हिंदी": "hi", "मराठी": "mr"}
    if "lang_code" not in st.session_state:
        st.session_state.lang_code = "en"
    choice = st.radio(
        "🌐 भाषा / Language / भाषा",
        list(opts.keys()),
        index=list(opts.values()).index(st.session_state.lang_code)
              if st.session_state.lang_code in opts.values() else 0,
        key="lang_selector",
    )
    st.session_state.lang_code = opts[choice]
    return st.session_state.lang_code
